version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d/${MYSQL_DATABASE}.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./.wordpress/plugins:/var/www/html/wp-content/plugins
      - ./.wordpress/themes:/var/www/html/wp-content/themes
      - ./.wordpress/uploads:/var/www/html/wp-content/uploads
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
